### ISSUE TITLE
Site appears to be down

### ISSUE THREAD

**Issue by Croebh** [haswellr/CritterDB#102]
If this is a bug or issue report, please follow the template below:

**Actual Behavior**:
 -  `What is the issue? *` The website, critterdb.com, times out when trying to visit the site
 -  `What is the expected behavior?` The website would load as normal

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 106.0.5249.119
 -  `OS: *` Windows 10

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

Had a few reports on the Avrae dev server about it being down since late last night, not entirely sure how long its been out.

**Comment by haswellr** [comment]
The server becomes unavailable every couple of months ever since I up-versioned Ubuntu. Not sure why yet, but it's very frustrating.

Mitigated for now, and you should be able to access the site again. I'll continue to monitor for a few days.

It was down for about 24 hours.

**Comment by Croebh** [comment]
Ah, yeah that sounds pretty frustrating haha. Thank you for the quick recovery and reply!
