### ISSUE TITLE
Unable to Sign in using Username

### ISSUE THREAD

**Issue by RChaffee07** [haswellr/CritterDB#107]
If this is a bug or issue report, please follow the template below:

**Actual Behavior**:
 -  `What is the issue? *` Unable to sign in using username, just says Invalid username.
 -  `What is the expected behavior?` to allow me to sign in using proper username

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` Newist verson 
 -  `OS: *` Windows

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by haswellr** [comment]
Resolved via email
