### ISSUE TITLE
An issue when using https://critterdb.com/#/bestiary with the https://avrae-ui.netlify.app/ bot in DISCORD

### ISSUE THREAD

**Issue by crystalkalem** [haswellr/CritterDB#109]
**Actual Behavior**:
 -  Missing Summoned Spirit abilities when using it to import via https://avrae-ui.netlify.app/
 -  I expect that when I create an action for "fey step" and paste the "fey step" description in, for it to be show up when I type !ma "fey spirit" 
 - Instead the only thing that shows up is the shortsword attack. Editing a generated attack will remove it's ability to show up when using the !ma "creature name". An example of this is to Generate a Pike attack to change its name to "Fey step" and swap out the attack macro for the "Fey Step" description, it will no longer show up in the bots readings. 

**Additional Information**:
 -  This issue is universal for all summoned creature abilities that aren't simple attacks, or casting defined spells.
 -  Using the Discord bot https://avrae-ui.netlify.app/

**Comment by haswellr** [comment]
Please check with the Avrae team on this!
