### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by mommothazaz123** [haswellr/CritterDB#11]
Recently, some users have expressed concern over the fact that CritterDB does not take advantage of SSL/TLS to encrypt user data. Looking at the server, it appears that CritterDB is built on the express.js framework, which supports SSL; I was wondering if you would like to work to do so, and offer to share insight if you want.

**Comment by haswellr** [comment]
Alright, got my PC set up again and set up SSL/TLS for the CritterDB server. Closing.
