### ISSUE TITLE
Multiple JS Errors and unable to edit/save creatures

### ISSUE THREAD

**Issue by Geekswordsman** [haswellr/CritterDB#15]
**Actual Behavior**:
 -  After creating a bestiary, I am able to create one creature.  Attempting to edit the creature or create a new one does not function; clicking Save & Finish does nothing.
 -  Save & Finish should close the current edit and save all updated information to the bestiary.

**Additional Information**:
 -  Opera
 -  v54.0.2952.51
 -  Chrome 
 -  v67.0.3396.99
 -  Windows 10 Pro

Attempted to send an e-mail report to contact@critterdb.com as mentioned in the registration e-mail; it failed with address not found.

Full details:

I am unable to save edits or new creatures to a brand new bestiary after creating the first creature.

When loading the bestiary, a 400 (Bad Request) is immediately logged as the result of a PUT command to:
https://www.critterdb.com/api/bestiaries/5b535bb67c719165ca2700c3

Clicking edit on a creature causes 25 errors - all of which are:
RangeError: Maximum call stack size exceeded
at oa (vendor.min.js:14)
at oa (vendor min.js:15) ....

Attempting to edit any text fields causes massive performance problems.

Clicking Save and Finish does not function and causes more Maximum call stack size exceeded errors.

These same problems occur when attempting to create a new creature.

I attempted to create a new bestiary and try again.  It allowed me to create a new creature, but attempting to edit or add a new one results in the same behavior problem.

Environment Information:

Windows 10 Professional
AMD FX 8350 Eight-Core Processor @ 4.00GHz
16.0GB RAM
Opera (v54.0.2952.51) and Chrome (v67.0.3396.99) browsers.

**Comment by haswellr** [comment]
Thanks for the detailed information. I am looking into it.

**Comment by haswellr** [comment]
Looks like a mongodb upgrade from 3.4 to 3.6 by the database host is causing issues.

**Comment by haswellr** [comment]
Fixed by updating mongoose 263eb8d251784bad713d3e8e9b551c3af59a43f7

**Comment by haswellr** [comment]
Will track the incorrect email issue here: https://github.com/haswellr/CritterDB/issues/16
