### ISSUE TITLE
I think it would be better if beast details only showed on click instead of hover.

### ISSUE THREAD

**Issue by melance** [haswellr/CritterDB#2]
When viewing my bestiary, it is hard to view the details of a creature because I seem to accidentally hover over one of the cards on the left hand side.  I think it would be better to only display the details when an item is clicked on instead of on hover.

**Comment by haswellr** [comment]
This is a great idea. I am making it so you can still hover to preview, but once you click on a creature that becomes your selected creature and will display if you are not hovering over any other creatures.
