### ISSUE TITLE
[Bugs] A collection of typos and bugs

### ISSUE THREAD

**Issue by badooga** [haswellr/CritterDB#26]
As there are multiple issues in this one post, I opted to condense the issue template as follows.

1. **Generated attacks with bonus damage have a misplaced comma.**
	- What I want: `11 (1d6 + 8) slashing damage plus 3 (1d6) bludgeoning damage.`
    - What I get: `11 (1d6 + 8) slashing damage, plus 3 (1d6) bludgeoning damage.`
2. **Auto-capitalization for languages is unsatisfactory.**
	- What I want: `Common, Infernal, Deep Speech` or `all, telepathy 120 ft.`
	- What I get: `Common, Infernal, Deep speech` or `All, Telepathy 120 ft.`
	- Suggested fix: Remove auto-capitalization of languages; in my opinion, the autofill list of already capitalized languages is enough to enforce the general "languages should be capitalized" formatting rule, and it doesn't cause issues with these exceptions to that rule.
3. **Legendary Actions have improper italics.**
	- What I want: bold names with a hanging indent. ![image](https://user-images.githubusercontent.com/33851191/52907160-53a6d080-3229-11e9-9367-89ae5139921f.png)
	- What I get: bold and italic names without a hanging indent. ![image](https://user-images.githubusercontent.com/33851191/52907172-8f419a80-3229-11e9-96ca-0caa42e09fad.png)
	- Note: This also requires a change in markdown exporting. When it comes to GM Binder and the Homebrewery format, the desired format can be acquired with the following text:
        ```>- **Action Name.** Legendary action description.```
		In HTML/CSS, such formatting can be achieved as described [here](https://www.thesitewizard.com/css/hanging-indents.shtml).
4. **Legendary Action text fails to account for the Proper Noun name checkbox when exported.**
	- What I want: `Zargon can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. Zargon regains spent legendary actions at the start of its turn.`
	- What I get: `The zargon can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The zargon regains spent legendary actions at the start of its turn.`
	- Note: This occurs when exporting to Homebrewery and to HTML; exporting to an Image does not create this problem.
5. **Autofilled creature abilities fail to account for proper nouns.**
	- What I want: `Zargon's weapon attacks are magical. When Zargon hits with any weapon, the weapon deals an extra 4d8 radiant damage.`
	- What I get: `The zargon's weapon attacks are magical. When the zargon hits with any weapon, the weapon deals an extra 4d8 radiant damage.`
	- Suggested fix: From what I saw of `creatureAbilities.json`, every ability is autofilled with a "the" included in there. E.g. `The {{name}}'s weapon attacks are magical.` I suggest that the `{{name}}` variable prepend the "the" (or "The", when starting a sentence) to the monster's name if it is not a proper noun, and then to remove it if it is one, and then for `creatureAbilities.json` to be updated accordingly.
6. **Export to Image creates an image with overlapping text.**
	- What I want: an image of my stat block.
	- What I get: Note that the white space that follows the stat block is a (transparent) part of the generated image. ![aboleth sarcoma](https://user-images.githubusercontent.com/33851191/52907508-ff9fea00-3230-11e9-9ab9-1b33b8cdf01b.png)

**Additional Information**:
 -  Browser Type: `Chrome`
 -  Browser Version: `72.0.3626.109 (Official Build) (64-bit) (cohort: Stable)`
 -  OS: `Windows 8.1`

**Comment by haswellr** [comment]
Thanks for all the finds. I fixed some today:

1. Fixed in https://github.com/haswellr/CritterDB/commit/7ef26180b8ae0213c5a9d1f5e04a45f382f8d419
2. Fixed in https://github.com/haswellr/CritterDB/commit/f96a06159c1f6caac58782c7e9248aa87c93e42b
3. Fixed in https://github.com/haswellr/CritterDB/commit/2f8f39df24c5cdf07b3c945efe79c363f3ee7f96
4. Fixed in https://github.com/haswellr/CritterDB/commit/5880493c6ff1e2d7c399b729f221f5e20402b254 by making legendary actions an editable field.
5. Still TODO
6. Image exporting looks correct for me so I will need to find a way to reproduce. I haven't put much time into that yet.

**Comment by badooga** [comment]
FYI, based on the official books, Legendary Action `h4` headers should not be italicized (both on the site and when exported):

Expected:
![image](https://user-images.githubusercontent.com/33851191/52969438-6383f900-337e-11e9-81a0-1fbf75f3d2d6.png)


Actual:
![image](https://user-images.githubusercontent.com/33851191/52969356-14d65f00-337e-11e9-87c8-884e336bac30.png)

Thank you again for all the hard work.

**Comment by badooga** [comment]
Two other issues I found:

1. If I have a creature with a language of `understands Common but can't speak`, it will look fine while on the site, but the Homebrewery export will still net me `Understands common but can't speak` (note the capitalization).

2. In addition to the unnecessary italicization of legendary actions mentioned above, the lines highlighted below cause issues when put into GM Binder, also pictured; this issue is fixed by the removal of these extra lines.

![image](https://user-images.githubusercontent.com/33851191/52970516-0ab65f80-3382-11e9-9720-2ce93041518b.png)
![image](https://user-images.githubusercontent.com/33851191/52970585-4cdfa100-3382-11e9-8d73-75de864e6a04.png)

**Comment by badooga** [comment]
Also, I realize now that for image exporting, your message `Your stat block will be saved as you see it here. Please ensure that it fits within the window.` refers to issue #6 of the OP. I'm not sure how you are generating these images in the first place, but surely there's a way to have that extra part of the stat block be put underneath the first part of it, rather than on top?

**Comment by haswellr** [comment]
> Also, I realize now that for image exporting, your message `Your stat block will be saved as you see it here. Please ensure that it fits within the window.` refers to issue 6 of the OP (was probably there before I pointed it out). I'm not sure how you are generating these images in the first place, but surely there's a way to have that extra part of the stat block be put underneath the first part of it, rather than on top?

Saving an image of a web page in javascript is actually remarkably janky. There's no 'convert HTML to image'. It saves it by making that part of the page a canvas using http://html2canvas.hertzen.com/, then converting the canvas to data and making it the target of a link, then faking a user click on the link. Unfortunately it can only handle what is on the page.

Alternatives would be to: 1. See if the library can be modified to not require everything to be on the screen. 2. Write some back-end code on top of Chromium to open the html in a browser then convert it to an image, then return it to the front end. This would work consistently but add a fair bit of a complexity to what is right now a pretty simple back-end.

**Comment by badooga** [comment]
I see. Well, at least the newer issues with languages and legendary actions are less complex than that.

**Comment by haswellr** [comment]
#5: Fixed by https://github.com/haswellr/CritterDB/commit/ffcfca7eee92974121141f40dd6e9601fda83fd1

Language capitalization when exported fixed by https://github.com/haswellr/CritterDB/commit/f276fb6ca99d2801893afaa4281c2c60642708e8

Fixed incorrect italicization of and newlines between legendary action abilities in https://github.com/haswellr/CritterDB/commit/82dcc40eda534b6724397669180eb9a59d8994b7

I think that is everything other than the export to image issues. I may eventually get to improving the export to image functionality, but it is going to be a lot of work so is not currently on my list. So, I'm going to resolve this one!
