### ISSUE TITLE
[Bug] Bestiaries Not Loading + other JavaScript Bugs

### ISSUE THREAD

**Issue by badooga** [haswellr/CritterDB#30]
**Actual Behavior**:
 -  `What is the issue?` As of just a few minutes ago, many of my bestiaries aren't loading. The only one that is loading is the one I was working on most recently and had open just before this happened.
- `Console Output` See below for the console output. This log appeared on every bestiary that has this problem. ![image](https://user-images.githubusercontent.com/33851191/52923929-4d335a00-32f8-11e9-8ff4-b981239a66bf.png)
- `What is the source?` Not sure. Based on this issue existing on both mobile and desktop, plus the console output above, I don't think it's something on my end like the cache (which I cleared during troubleshooting). I originally thought my data was lost, but a few `Ctrl + F5`s gave me glimpses of some content in the bestiaries, supporting the console output in that it's just not loading for some reason.

**Additional Information**:
 -  `Browser Type:` Chrome, both desktop and mobile
 -  `Browser Version:` Latest version of both; desktop: `72.0.3626.109 (Official Build) (64-bit) (cohort: Stable)`
 -  `OS:` Windows 8.1

**Comment by badooga** [comment]
Update: I am able to access the affected bestiaries by opening the bestiary > making a new monster > hitting save finish.

Additionally, I am also able to access them if I open the bestiary > go back to My Critters > open the bestiary again now that it is at the top of the list. However, the first monster of every bestiary seems to have an issue where its challenge rating does not load:

![image](https://user-images.githubusercontent.com/33851191/52926618-7e198c00-3304-11e9-91ea-f65bfa643dc4.png)

When I try to click the edit button or any of the exporting options for an affected error, nothing happens, and I get the following error log:

![image](https://user-images.githubusercontent.com/33851191/52926822-7d352a00-3305-11e9-8c17-d73337169842.png)

I imagine that this and the original issue are related, but I wouldn't really know anything about that.

**Comment by badooga** [comment]
Lastly, when editing any monster (new or old), the hit dice seem to be having some issues:
![image](https://user-images.githubusercontent.com/33851191/52927058-a0aca480-3306-11e9-9c93-3c6129c940d1.png)

Console output:
![image](https://user-images.githubusercontent.com/33851191/52927142-ff721e00-3306-11e9-8030-ac4b59efd7d5.png)

**Comment by badooga** [comment]
As an addendum to the first two issues, it's worth mentioning that I'm seeing them when viewing other peoples' bestiaries, too:

![image](https://user-images.githubusercontent.com/33851191/52927302-be2e3e00-3307-11e9-8fc7-e75694a95e08.png)

![image](https://user-images.githubusercontent.com/33851191/52927307-c5ede280-3307-11e9-9ed3-a0033de00a9b.png)

![image](https://user-images.githubusercontent.com/33851191/52927325-e9b12880-3307-11e9-8f07-130822f8725b.png)

I just reproduced this stuff in Firefox, too, so it doesn't seem to be a me issue or a browser specific issue.

**Comment by haswellr** [comment]
Ugh. This was my fault for hastily pushing some code before rushing out the door for the evening. This looks like two issues:

1. A typo in the skills data file plus some questionable code caused a "javascript NPE" for any creature that had the Intimidation skill. Fixed the typo and made the code a bit more defensive in https://github.com/haswellr/CritterDB/commit/125a933cef990dd9f1ac1f161421f1881ef8cbaf
2. The Challenge and hit die issues look like you have a mismatch of cached versions loaded. I've manually busted the JS cache here https://github.com/haswellr/CritterDB/commit/2b953c3934b8737af4ac7173a55374f58511bf89

If you are still seeing this please let me know. It is working fine on my end on PC and phone but I may have missed something.

**Comment by badooga** [comment]
Looks like all the issues are gone on my end. Thank you for the quick fix.
