### ISSUE TITLE
Sizing error in Creature Editor

### ISSUE THREAD

**Issue by Siravia** [haswellr/CritterDB#32]
The size of the creature is no longer editable to show as 'fine, diminutive, tiny, small, medium,' etc. It now shows up as {"hitDieSize":4}, {"hitDieSize":6}, etc.

**Comment by haswellr** [comment]
@Siravia this should just be a temporary caching error. Are you still seeing this? (sorry for the super late response on this one)

**Comment by Siravia** [comment]
It’s fine. No, I am no longer seeing this. The error reversed itself last week.
