### ISSUE TITLE
Error with Calculate Challenge Rating

### ISSUE THREAD

**Issue by Pascal-Santiago** [haswellr/CritterDB#34]
If this is a bug or issue report, please follow the template below:

**Actual Behavior**:
 -  `What is the issue? *` Using the Calculate Challenge Rating option does not accurately calculate a creature's challenge rating when a Save DC is inputted. As far as I can tell, all it does is subtract .5 from the offensive CR if there is a value greater than ten.
 -  `What is the expected behavior?` Calculate the CR based on Save DCs according to the table.

**Additional Information**:
 -  `Browser Type: *`Chrome
 -  `Browser Version: *`
 -  `OS: *`Windows

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by haswellr** [comment]
The save DC does indeed seem to be having some strange effects on the offensive CR. I am looking into it.

**Comment by haswellr** [comment]
The logic was just completely flawed. Not sure what I was thinking at the time! It is fixed now, although your cache may need some time to clear and pull the updated files.
