### ISSUE TITLE
critters will not export the creature.  I've tried on safari, Firefox, and chrome.

### ISSUE THREAD

**Issue by RTH20PODCAST** [haswellr/CritterDB#38]
If this is a bug or issue report, please follow the template below:

**Actual Behavior**:
 -  `What is the issue? *`
 -  `What is the expected behavior?`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by haswellr** [comment]
Not sure how this bug got in there, but it was an easy fix. Should be working now! Thank you for reporting it.
