### ISSUE TITLE
Feature Request: NonPublic-Published Bestiary

### ISSUE THREAD

**Issue by DrWiFi** [haswellr/CritterDB#40]
I would like to make a feature request to be able to publish Non-Public Bestiaries. 
The use case is for those who want to have their monsters into Avrae, but not wanting the whole world to see.
Currently you have to Publish -> Import -> Delete for any changes to your critters.

**Comment by haswellr** [comment]
Avrae has integrated with CritterDB in such a way that its users will not have to log in to CritterDB to get their data from it. This has the benefit of easy access, but the downside that everything has to be public.

While I can't get around needing some form of login to access private bestiaries, what I can do is have an option to make a bestiary publicly accessible, but not actually publish it on the site. So if anyone has the link, they can see it, but the link will not be published, if that makes sense. I think this is a good idea!

**Comment by DrWiFi** [comment]
That is essentially what I was going for. Thanks :)

**Comment by haswellr** [comment]
Took me a while, but this was completed in https://github.com/haswellr/CritterDB/issues/56. Avrae has not yet integrated with it, but they are planning to.
