### ISSUE TITLE
Passive perception should be editable

### ISSUE THREAD

**Issue by Tiffys** [haswellr/CritterDB#41]
**Actual Behavior**:
 -  `What is the issue? *` Passive perception is currently only calculated based on 10+wis modifier
 -  `What is the expected behavior?` It should be editable because some monsters don't follow that calculation. Guard Drake for instance has 12 passive perception yet only 10 (+0) WIS.

**Additional Information**:
 -  `Browser Type: *` Firefox
 -  `Browser Version: *` 47.0.1
 -  `OS: *` Windows 8.1 Pro

**Comment by haswellr** [comment]
Hey,

Passive perception is based on the creature's Perception skill, following the rules of 5E. The Guard Drake seems to be proficient in Perception (you can see Perception +2 in its Skills line), so it ends up with a passive perception of 12. I think this is the correct behavior for CritterDB.
