### ISSUE TITLE
Spells don't export into Avrae

### ISSUE THREAD

**Issue by uuuu777777** [haswellr/CritterDB#46]
If this is a bug or issue report, please follow the template below:

**Actual Behavior**:
 -  `What is the issue? *` I can create attacks but when I generate a spell or ability, it does list it in Avrae, but I cannot use it when in !init order
 -  `What is the expected behavior?` I should be able to use !cast <spell> -t <target> and it use the spell listed from the monster

**Additional Information**:
 -  `Browser Type: *` Discord
 -  `Browser Version: *` No idea
 -  `OS: *` Windows 7

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by haswellr** [comment]
Hey,

Please check with the Avrae team on this! Nothing has changed with the spells or abilities in some time. If they investigate and find that there is something wonky on CritterDB's end then please let me know.
