### ISSUE TITLE
Is there an API to import monsters into Python bot?

### ISSUE THREAD

**Issue by the-machine-preacher** [haswellr/CritterDB#54]
Is there an API to import monsters into Python bot? I'm pretty sure there is one as Avrae is able to do it! Specifically, how do I get the token, critter and database id? 

I wrote a Python Discord bot and I wished to download the monsters for "Descent into Avernus": https://critterdb.com/#/publishedbestiary/view/5e7538d59bfcf04c995356a3

The monster I wished to get is the "Abyssal Chicken", which is the first one. How do I get the token, database and critter id to get it?

**Comment by haswellr** [comment]
Responded via email.

TLDR:
* Use the endpoints defined here: https://github.com/haswellr/CritterDB/blob/master/server/server.js#L68
* Specifically, for the published bestiary mentioned, make a GET request to this URL: https://critterdb.com/api/publishedbestiaries/5e7538d59bfcf04c995356a3

**Comment by the-machine-preacher** [comment]
Hey, thanks for that! Just one more question: how do I find the name and author of the the actual bestiary itself? For instance, of the aforementioned bestiary: https://critterdb.com/api/publishedbestiaries/5e7538d59bfcf04c995356a3
