### ISSUE TITLE
Ranged attacks using STR modifier instead of DEX modifier

### ISSUE THREAD

**Issue by schnautzr** [haswellr/CritterDB#67]
**Actual Behavior**:
 -  `What is the issue? *` Added a longbow ranged attack action to a creature ([Arbor-Colossus.zip](https://github.com/haswellr/CritterDB/files/4801965/Arbor-Colossus.zip)). CritterDB used the STR modifier.

 -  `What is the expected behavior?` Longbow should use the DEX modifier.

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 83.0.4103.97 (Official Build) (64-bit)
 -  `OS: *` Windows 10 (64-bit)

**Comment by haswellr** [comment]
Thanks for reporting this. Looks like this was a long-standing bug that only occurs for ranged attacks when a creature's DEX mod is less than their STR mod. It is now fixed.
