### ISSUE TITLE
5e tools-JSON: Download and copy not functional

### ISSUE THREAD

**Issue by saramaggie** [haswellr/CritterDB#68]
**Actual Behavior**:
 -  `What is the issue? *`
When trying to export a critter to 5e tools- JSON it does not work. I have that this problem works in two ways. 
     - The download simply doesn't work. The button is greyed out and unresponsive.
     - The copy function, however, is a bit more interesting. The button is still greyed out but if one has copied any critter (same result when the previous copy is the same or another critter) in any other format without reloading the page it gives you the message that you have copied the creature to the clipboard, but it's still the data from the previous copy.
-  `What is the expected behavior?`
To download/copy a 5e tools-JSON for specified critter

**Additional Information**:
 -  `Browser Type: *` 
    1. Chrome
    2. Firefox
 -  `Browser Version: *`
    1. Version 83.0.4103.116 (Official Build) (64-bit)
    2. 78.0.1 (64-bit)
 -  `OS: *`
Windows 10

**Comment by haswellr** [comment]
This is fixed now, sorry about that.
