### ISSUE TITLE
Technical Issues with site

### ISSUE THREAD

**Issue by jman0955** [haswellr/CritterDB#75]
I’m not able to log in at all, and it won’t even send a password reset email if I try that. It just keeps saying invalid username after  a while of doing nothing, when I know it’s the right information. The main page is also fully blank, when it normally has some of the different created stat blocks on display on the main page. Looks like this was an issue last year too. It work on my laptop with Microsoft Edge, and it won’t work on my iPhone with Safari either.

**Comment by haswellr** [comment]
There seems to have been server issues. Fixed now. Please let me know if you're still having issues.
