### ISSUE TITLE
Invalid Username Bug

### ISSUE THREAD

**Issue by Eriskan** [haswellr/CritterDB#86]
If this is a bug or issue report, please follow the template below:

**Actual Behavior**:
 -  `What is the issue? *Unable to log into CritterDB, says "Invalid Username" 
![image](https://user-images.githubusercontent.com/95077439/143561572-f57739c4-49f7-4ddc-992a-c59dd052c473.png)
The Username however is correct, along with the password.
![image](https://user-images.githubusercontent.com/95077439/143561793-a4835c68-febb-4597-bc5d-2531ee05fd8d.png)
For some reason, the Current Password is long, while I have made it short, I've tried making a new password twice already, and it's the same long message. 
So far my solution has been to reset my password, but I hope there's another way to do this
 -  `What is the expected behavior?` Being able to log in

**Additional Information**:
 -  `Browser Type: `*Chrome
 -  `Browser Version: `*96.0.4664.45
 -  `OS: *`

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by haswellr** [comment]
Looks like you had a space after your name ("Ericia " rather than "Ericia"). I removed the space for you.

Issue to disallow spaces from usernames, to avoid this annoyance in the future: https://github.com/haswellr/CritterDB/issues/49
