### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by guntam** [haswellr/CritterDB#91]
If this is a bug or issue report, please follow the template below:

**Actual Behavior**:
 -  `What is the issue? *` I can't log in. It says the "invalid username" (my username is anogiri) and if I try to reset password using the e-mail I signed up with, it says the e-mail is not on the system.
 -  `What is the expected behavior?` I should be able to log in.

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` Version 99.0.4844.51 (Official Build) (64-bit)
 -  `OS: *` Windows 10

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by haswellr** [comment]
There is something going wrong with the server. Nobody is able to log in, so this is not isolated to a single account. The data in the database is fine, as far as I can tell, so this is more an issue with accessing your account than having lost your account (in case that alleviates concerns). This may be related to recent OS updates I performed a few days back.

I tried some quick debugging steps but was unable to resolve the issue this morning. I unfortunately cannot spend more time on it til tonight, about 14 hours from now. The site will likely remain down until then.

I'm very sorry for the inconvenience. Please follow this issue for updates.

**Comment by haswellr** [comment]
Turns out the database is out of space. I am upgrading now, hoping for resolution in the next couple of hours.

**Comment by haswellr** [comment]
The fix (as always) wasnt as smooth as expected. I will take a further look tonight. Unfortunately I'm not able to commit a ton of time until Monday evening, but hoping I can fix in my spare time.

**Comment by haswellr** [comment]
Fixed at last! Very sorry for the delay. I strive to be more on top of issues like this, but had a bunch of commitments the past couple of days.
