### ISSUE TITLE
Cannot log in to CritterDB

### ISSUE THREAD

**Issue by safe-by-voice** [haswellr/CritterDB#98]
If this is a bug or issue report, please follow the template below:

**Actual Behavior**:
 -  `What is the issue? *` Cannot log in to my CritterDB account; I try to submit my certified password and it won't accept it. Even when I submit a 'reset my password' link it doesn't send me one.
 -  `What is the expected behavior?` I can normally log in to my account.

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *` Version 102.0.5005.115
 -  `OS: *` Windows 11

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by haswellr** [comment]
Check https://github.com/haswellr/CritterDB/issues/97
